#! /bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="xinetd"
NAME=xinetd
DAEMON_CONF=/etc/xinetd.conf
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/S99xinetd

#
#	Function that starts the daemon/service.
#
d_start() {
	if [ -f $DAEMON_CONF ]
	then
		service_n=$(grep -n 'service tftp' $DAEMON_CONF | awk -F: '{print $1}')
		server_args_n=$(tail -n +$service_n $DAEMON_CONF | grep -n 'server_args' | awk -F: '{print $1}')
		if [ $service_n ] && [ $server_args_n ]
		then
			server_args_n=$(expr $service_n + $server_args_n - 1)
			server_dir=$(sed -n "${server_args_n}p" $DAEMON_CONF | awk '{print $NF}')
			mkdir -p $server_dir
			chmod 777 $server_dir
		else
			mkdir -p /tftpboot
			chmod 1777 /tftpboot
		fi
	fi
	$DAEMON
}

#
#	Function that stops the daemon/service.
#
d_stop() {
	killall -q $NAME
}

#
#	Function that sends a SIGHUP to the daemon/service.
#
d_reload() {
	d_start
	d_stop
}

case "$1" in
  start)
	echo -n "Starting $DESC: "
	d_start
	echo "done"
	;;
  stop)
	echo -n "Stopping $DESC: "
	d_stop
	echo "done"
	;;
  #reload)
	#
	#	If the daemon can reload its configuration without
	#	restarting (for example, when it is sent a SIGHUP),
	#	then implement that here.
	#
	#	If the daemon responds to changes in its config file
	#	directly anyway, make this an "exit 0".
	#
	# echo -n "Reloading $DESC configuration..."
	# d_reload
	# echo "done."
  #;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC: "
	d_stop
	sleep 1
	d_start
	echo "done"
	;;
  *)
	# echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
